import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Menu, X, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="shell header-inner"><Link to="/" className="wordmark" aria-label="BHRYPN home"><span className="brand-mark" />BHR<span className="text-primary">YPN</span></Link><nav className="desktop-nav" aria-label="Main navigation"><Link to="/">Home</Link><Link to="/" hash="about">About Us</Link><Link to="/" hash="leadership">Leadership Board</Link><Link to="/events">Events</Link></nav><Button asChild variant="outline" className="join-button hidden md:inline-flex"><Link to="/contact">Contact / Join Us <ArrowUpRight /></Link></Button><Button variant="ghost" size="icon" className="md:hidden" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <nav className="mobile-nav shell" aria-label="Mobile navigation" onClick={() => setOpen(false)}><Link to="/">Home</Link><Link to="/" hash="about">About Us</Link><Link to="/" hash="leadership">Leadership Board</Link><Link to="/events">Events</Link><Link to="/contact">Contact / Join Us</Link></nav>}</header>;
}
export function SiteFooter() { return <footer className="site-footer"><div className="shell footer-inner"><Link to="/" className="wordmark"><span className="brand-mark" />BHRYPN</Link><p>Business and Human Rights<br />Young Professionals Network</p><div className="footer-links"><Link to="/events">Events</Link><Link to="/contact">Contact / Join Us <ArrowUpRight size={14} /></Link></div><span className="footer-copy">© 2026 BHRYPN</span></div></footer>; }
export function JoinBand() { return <section className="join-band shell"><p className="eyebrow">Your next connection starts here</p><h2 className="section-title">A shared purpose.<br /><span className="text-primary">A stronger community.</span></h2><Button asChild className="pill mt-8"><Link to="/contact">Join the network <ArrowUpRight /></Link></Button></section>; }
export function pageHead(title: string, description: string) { return { meta: [{ title: `${title} — BHRYPN` }, { name: 'description', content: description }, { property: 'og:title', content: `${title} — BHRYPN` }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }; }
